"use client"
import React, { useState, useEffect } from 'react';
import { initializeApp, getApps } from 'firebase/app';
import type { MessagePayload, Messaging } from 'firebase/messaging';

// --- Firebase Configuration ---
const firebaseConfig = {
  apiKey: "AIzaSyBoS91U_Zfppcv1R_bAm3kQthwN5CZOsiI",
  authDomain: "cloud-computing-arknights.firebaseapp.com",
  projectId: "cloud-computing-arknights",
  storageBucket: "cloud-computing-arknights.firebasestorage.app",
  messagingSenderId: "977633385476",
  appId: "1:977633385476:web:66871b4a2182ba42196951",
  measurementId: "G-19JP5NW39G"
};

/**
 * Firebase Messaging is not available in every runtime (SSR, some browsers, etc).
 * Never initialize it at module scope; gate it behind `isSupported()` in the browser.
 */
let messagingInitPromise: Promise<Messaging | null> | null = null;
let serviceWorkerRegistration: ServiceWorkerRegistration | null = null;

async function getMessagingSafe(): Promise<Messaging | null> {
  if (typeof window === "undefined") return null;

  if (!messagingInitPromise) {
    messagingInitPromise = (async () => {
      const { isSupported, getMessaging } = await import("firebase/messaging");
      const supported = await isSupported();
      if (!supported) return null;

      const app = getApps().length ? getApps()[0]! : initializeApp(firebaseConfig);
      return getMessaging(app);
    })().catch((err) => {
      console.warn("Failed to initialize Firebase Messaging:", err);
      return null;
    });
  }

  return messagingInitPromise;
}

// Cache Token
let cachedToken: string | null = null;
const VAPID_KEY = 'BKN0bH0kaCV2nhLSU3KEkk60XfTwfyISgu3y9UalnEUVzy6s0omDAUYiqeBP95H2XN-awF8jbaYa0eGFmYEGagc';

// Configure backend URL (in production, this should be in .env file)
const API_BASE_URL = "http://127.0.0.1:8000";

// --- 1. Define interfaces (DTO) ---
// These interfaces should match the response_model from your FastAPI backend
interface UploadResponse {
  status: string;
  filename: string; // UUID filename generated by backend
  message: string;
}

interface UrlResponse {
  url: string; // Signed URL
}

const ImageUploader: React.FC = () => {
  // --- 2. State management ---
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  
  // Data display after successful upload
  const [uploadedUuid, setUploadedUuid] = useState<string | null>(null);
  const [displayUrl, setDisplayUrl] = useState<string | null>(null);

  // --- Firebase Setup & Service Worker ---
  useEffect(() => {
    let unsubscribe: (() => void) | undefined;

    (async () => {
      const messaging = await getMessagingSafe();
      if (!messaging) return;

      // Register Service Worker (required for FCM in most browsers)
      if ("serviceWorker" in navigator) {
        try {
          serviceWorkerRegistration = await navigator.serviceWorker.register("/firebase-messaging-sw.js");
          console.log("Service Worker registration successful with scope: ", serviceWorkerRegistration.scope);
        } catch (err) {
          console.log("Service Worker registration failed: ", err);
        }
      }

      // Listen for foreground messages
      const { onMessage } = await import("firebase/messaging");
      unsubscribe = onMessage(messaging, (payload: MessagePayload) => {
        console.log("Received foreground message:", payload);
        const title = payload.notification?.title || "New Message";
        const body = payload.notification?.body || "";

        // Demo-friendly: always show a simple popup so it's obvious the message arrived.
        // (System notifications can be blocked/silenced by browser/OS settings.)
        alert(`${title}: ${body}`);

        // Optional: also try a system notification if available/allowed.
        if (typeof window !== "undefined" && "Notification" in window && Notification.permission === "granted") {
          try {
            new Notification(title, { body, icon: "/icon.svg" });
          } catch {
            // ignore
          }
        }
      });
    })();

    return () => unsubscribe?.();
  }, []);

  /**
   * Get FCM Token
   */
  async function getFcmToken(): Promise<string | null> {
    if (cachedToken) {
      return cachedToken;
    }

    if (typeof window === "undefined" || !("Notification" in window)) {
      return null;
    }

    try {
      const permission = await Notification.requestPermission();
      
      if (permission === 'granted') {
        const messaging = await getMessagingSafe();
        if (!messaging) return null;

        const { getToken } = await import("firebase/messaging");
        const token = await getToken(messaging, {
          vapidKey: VAPID_KEY,
          serviceWorkerRegistration: serviceWorkerRegistration ?? undefined,
        });
        if (token) {
          console.log('Token retrieved:', token);
          cachedToken = token;
          return token;
        }
      } else {
        console.warn('Notification permission denied');
      }
    } catch (error) {
      console.error('Error retrieving token:', error);
    }
    return null;
  }

 // #########################################################
 // core logic for image upload and get signed url to display image
 // #########################################################
  // --- 3. Handle file selection ---
  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files.length > 0) {
      setSelectedFile(event.target.files[0]);
      // Reset previous state
      setError(null);
      setUploadedUuid(null);
      setDisplayUrl(null);
    }
  };

  // --- 4. Core logic: upload -> get ID -> get signed URL ---
  const handleUpload = async () => {
    if (!selectedFile) {
      setError("Please select an image first");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // Step 0: Get FCM Token
      const fcmToken = await getFcmToken();
      if (!fcmToken) {
          console.warn("Could not get FCM token, proceeding without it.");
      }

      // Step A: Create FormData
      const formData = new FormData();
      formData.append("file", selectedFile);
      if (fcmToken) {
          formData.append("fcm_token", fcmToken);
      }

      // Step B: send upload request
      const uploadRes = await fetch(`${API_BASE_URL}/image/upload`, {
        method: "POST",
        body: formData,
      });

      if (!uploadRes.ok) {
        throw new Error(`Upload failed: ${uploadRes.statusText}`);
      }

      const uploadData: UploadResponse = await uploadRes.json();
      const uuidFilename = uploadData.filename;
      setUploadedUuid(uuidFilename); // save UUID

      // Step C: Get signed URL using UUID
      const urlRes = await fetch(`${API_BASE_URL}/image/${uuidFilename}`, {
        method: "GET",
      });
      console.log(urlRes);
      if (!urlRes.ok) {
        throw new Error("failed to get signed url");
      }

      const urlData: UrlResponse = await urlRes.json();
      setDisplayUrl(urlData.url); // Save and display URL

    } catch (err: any) {
      console.error(err);
      setError(err.message || "unknown error");
    } finally {
      setLoading(false);
    }
  };

  // --- 5. Render UI ---
  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h1 style={styles.title}>☁️ Image Upload Demo</h1>

        {/* upload area */}
        <div style={styles.inputGroup}>
          <input 
            type="file" 
            accept="image/*" 
            onChange={handleFileChange}
            style={styles.fileInput} 
          />
          <button 
            onClick={handleUpload} 
            disabled={!selectedFile || loading}
            style={loading || !selectedFile ? styles.buttonDisabled : styles.button}
          >
            {loading ? "Processing..." : "Upload Image"}
          </button>
        </div>

        {/* error hint */}
        {error && <div style={styles.error}>{error}</div>}

        {/* Result display area */}
        {displayUrl && (
          <div style={styles.resultArea}>
            <div style={styles.successBadge}>✅ Upload Success</div>
            
            <img src={displayUrl} alt="Uploaded" style={styles.imagePreview} />
            
            <div style={styles.infoBox}>
              <p style={styles.infoText}>
                <strong>Backend Storage Filename (UUID):</strong><br/>
                {uploadedUuid}
              </p>
              <p style={styles.infoText}>
                <strong>Signed URL:</strong><br/>
                <a href={displayUrl} target="_blank" rel="noreferrer" style={styles.link}>
                  Click to open image in new window
                </a>
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// --- 6. Simple style object (CSS-in-JS) ---
// Using inline styles for easy copy-paste usage
// In production, you can use .css files or Tailwind
const styles: { [key: string]: React.CSSProperties } = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    padding: '40px 20px',
    backgroundColor: '#f5f7fa',
    minHeight: '100vh',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  card: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '12px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    width: '100%',
    maxWidth: '500px',
  },
  title: {
    textAlign: 'center',
    marginBottom: '24px',
    color: '#333',
    fontSize: '1.5rem',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '20px',
  },
  fileInput: {
    padding: '10px',
    border: '1px dashed #ccc',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  button: {
    backgroundColor: '#007bff',
    color: 'white',
    padding: '12px',
    border: 'none',
    borderRadius: '6px',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  buttonDisabled: {
    backgroundColor: '#a0cfff',
    color: 'white',
    padding: '12px',
    border: 'none',
    borderRadius: '6px',
    fontSize: '1rem',
    cursor: 'not-allowed',
  },
  error: {
    backgroundColor: '#ffebee',
    color: '#c62828',
    padding: '10px',
    borderRadius: '6px',
    marginBottom: '20px',
    fontSize: '0.9rem',
    textAlign: 'center',
  },
  resultArea: {
    marginTop: '20px',
    animation: 'fadeIn 0.5s',
  },
  successBadge: {
    textAlign: 'center',
    color: '#2e7d32',
    fontWeight: 'bold',
    marginBottom: '10px',
  },
  imagePreview: {
    width: '100%',
    height: 'auto',
    borderRadius: '8px',
    border: '1px solid #eee',
    marginBottom: '15px',
  },
  infoBox: {
    backgroundColor: '#f8f9fa',
    padding: '15px',
    borderRadius: '8px',
    fontSize: '0.85rem',
    wordBreak: 'break-all',
  },
  infoText: {
    marginBottom: '10px',
    lineHeight: '1.4',
    color: '#555',
  },
  link: {
    color: '#007bff',
    textDecoration: 'none',
  }
};

export default ImageUploader;
